import jwt from "jsonwebtoken";
import { NextResponse } from "next/server";

// Utils
import connectDB from "@/lib/db";
import { setAuthCookies } from "@/utils/cookies.util";

// Models
import User from "@/models/User.model";

/**
 * --- Token Exchange API Route ---
 *
 * - Exchanges a short-lived magic link token for long-lived session cookies
 * - Validates the exchange token generated by the webhook
 * - Sets HttpOnly cookies for accessToken and refreshToken
 */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { token } = body;

    if (!token) {
      return NextResponse.json(
        { error: "Exchange Error: Token is required" },
        { status: 400 },
      );
    }

    const jwtSecret = process.env.JWT_SECRET as string;

    await connectDB();

    // Find user by magicToken
    const user = await User.findOne({
      magicToken: token,
      magicTokenExpiresAt: { $gt: new Date() }, // Token must not be expired
    });

    if (!user) {
      return NextResponse.json(
        { error: "Exchange Error: Invalid or expired token" },
        { status: 401 },
      );
    }

    // Immediately burn the token so it cannot be used again
    await User.findByIdAndUpdate(user._id, {
      $unset: { magicToken: "", magicTokenExpiresAt: "" },
    });

    // Generate Long-Lived Tokens
    const accessToken = jwt.sign(
      { userId: user._id, role: user.role },
      jwtSecret,
      { expiresIn: "15m" },
    );

    const refreshToken = jwt.sign({ userId: user._id }, jwtSecret, {
      expiresIn: "7d",
    });

    // Update refresh token in DB
    await User.findByIdAndUpdate(user._id, { $set: { refreshToken } });

    // Create response
    const response = NextResponse.json({
      success: true,
      user: {
        id: user._id,
        displayName: user.displayName,
        phoneNumber: user.phoneNumber,
        role: user.role,
      },
    });

    // Set auth cookies and return response₹
    return setAuthCookies(response, { accessToken, refreshToken });
  } catch (err: any) {
    console.error("Token Exchange Error. ERR: ", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
